services:
  - type: web
    name: ai-code-reviewer-backend
    runtime: node
    plan: free
    rootDirectory: BackEnd
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: GOOGLE_API_KEY
        sync: false
    env: node
